version: '3'

services:
  db:
    image: 'postgres:14-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    env_file:
      - '.env'
  redis:
    image: 'redis:latest'
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
    command:
      - redis-server
  sidekiq:
    depends_on:
      - 'redis'
    build: .
    volumes:
      - .:/app
    command: bundle exec sidekiq
    env_file:
      - '.env'
  app:
    depends_on:
      - 'db'
      - 'redis'
      - 'sidekiq'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    env_file:
      - '.env'
volumes:
  redis:
  postgres:
